language: d

arch:
  - amd64
  - arm64

os:
  - linux
  - osx


d:
 - ldc-beta
 - ldc-1.23.0
 - ldc-1.22.0
 - ldc-1.21.0
 - ldc-1.20.1
 - ldc-1.19.0
 - ldc-1.18.0
 - ldc-1.17.0
 - dmd-beta
 - dmd-2.093.1
 - dmd-2.092.1
 - dmd-2.091.1
 - dmd-2.090.1
 - dmd-2.089.1
 - dmd-2.088.1
 - dmd-2.087.1
 - gdc

matrix:
  allow_failures:
   - d: gdc
   - d: dmd-beta
     arch: arm64
   - d: dmd-2.093.1
     arch: arm64
   - d: dmd-2.092.1
     arch: arm64
   - d: dmd-2.091.1
     arch: arm64
   - d: dmd-2.090.1
     arch: arm64
   - d: dmd-2.089.1
     arch: arm64
   - d: dmd-2.088.1
     arch: arm64
   - d: dmd-2.087.1
     arch: arm64

script:
  - dub test --compiler=${DC} gfm:math
  - dub test --compiler=${DC} gfm:integers

